In [1]:
import numpy as np

In [25]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([86, 93, 100, 115, 120, 136])
#x = np.array([126, 128, 128, 130, 130, 132])
#y = np.array([78, 80, 82, 82, 84, 86])

In [27]:
mean_x = np.mean(x)
mean_y = np.mean(y)
std_x = np.std(x, ddof=1)
std_y = np.std(y, ddof=1)
mean_x, mean_y#, std_x, std_y

(3.5, 108.33333333333333)

In [28]:
_x = (x - mean_x) 
_y = (y - mean_y) 
_x, _y

(array([-2.5, -1.5, -0.5,  0.5,  1.5,  2.5]),
 array([-22.33333333, -15.33333333,  -8.33333333,   6.66666667,
         11.66666667,  27.66666667]))

In [29]:
Z = np.vstack((_x, _y)).T
Z

array([[ -2.5       , -22.33333333],
       [ -1.5       , -15.33333333],
       [ -0.5       ,  -8.33333333],
       [  0.5       ,   6.66666667],
       [  1.5       ,  11.66666667],
       [  2.5       ,  27.66666667]])

In [30]:
cov_matrix = np.cov(Z, rowvar=False)
cov_matrix

array([[  3.5       ,  34.6       ],
       [ 34.6       , 349.86666667]])

In [31]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
eigenvalues, eigenvectors

(array([7.74813792e-02, 3.53289185e+02]),
 array([[-0.99514335, -0.09843632],
        [ 0.09843632, -0.99514335]]))

In [24]:
# Step 4: Compute principal components
principal_components = Z @ eigenvectors
principal_components
#mean_x, mean_y, std_x, std_y, cov_matrix, eigenvalues, eigenvectors, principal_components

array([[ 0.06800833,  4.99953747],
       [-0.37003933,  2.20523715],
       [ 0.80808699,  0.58906316],
       [-0.80808699, -0.58906316],
       [ 0.37003933, -2.20523715],
       [-0.06800833, -4.99953747]])